### ISSUE TITLE
Add php-sqlite3 dependency for backups

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/spip_ynh#10]
![Screenshot from 2020-01-06 15-02-28](https://user-images.githubusercontent.com/108437/71822661-b39ea380-3095-11ea-9cf9-294424ce8eab.png)

```
apt -uVf install php-sqlite3 
```
solved it.

**Comment by kay0u** [comment]
Thank you for your report, it should be fixed now.
