### ISSUE TITLE
IMG : impossible to upload or impossible to access

### ISSUE THREAD

**Issue by majoux** [YunoHost-Apps/spip_ynh#13]
Sur un spip fraichement installé : 
Impossible d'uploader une image dans un nouvel article 
"Le téléchargement des fichiers du type de 20191229course.jpg n’est pas autorisé"

Si je transfère le dossier IMG venant d'un autre site spip (vieux mais à jour et n'était pas sur yunohost), je ne peux pas accéder aux images, j'obtiens une erreur 403 Forbidden. (au préalable j'ai bien mis l'owner en `chmod -R spip:spip IMG` )

**Comment by kay0u** [comment]
Bonjour, pour ajouter un nouveau type de fichier, veuillez vous référer à cette documentation: https://www.spip.net/fr_article2002.html#Ajouter-un-nouveau-type-de-fichier

**Comment by brunob** [comment]
@kay0u SPIP prend en charge les jpg sans problème, amha en mode devinette @majoux a un problème d'init de la table `spip_type_documents` qui ne s'est pas peuplée lors de l'installation, pour le résoudre il suffit de passer par la page de maintenance qui permet de lancer la réparation de la base de données.

Il faudrait tout de même vérifier que le package spip de yunohost peuple bien cette table à l'install.

**Comment by kay0u** [comment]
Effectivement il y avait bien un problème lors de l'installation via YunoHost. #15 doit régler ce problème.

Une simple mise à jour doit normalement patch le problème.
