### ISSUE TITLE
Interface privé inaccessible depuis la mise à jour 3.2.8~ynh1

### ISSUE THREAD

**Issue by majoux** [YunoHost-Apps/spip_ynh#19]
Le site public fonctionne correctement, il est possible de se loguer normalement en http et le bouton en bas "se déconnecter" prouve que la connection est OK.
Quand on se rend sur l'adresse https://site.fr/ecrire/ (en tapant l'adresse ou par le lien) une page blanche s'ouvre.
Rien ne s'affiche.
Voici le code source de la page en question :
```

<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ltr fr no-js ie ie6 lte9 lte8 lte7" xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr" dir="ltr"> <![endif]-->
<!--[if IE 7 ]>    <html class="ltr fr no-js ie ie7 lte9 lte8 lte7" xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr" dir="ltr"> <![endif]-->
<!--[if IE 8 ]>    <html class="ltr fr no-js ie ie8 lte9 lte8" xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr" dir="ltr"> <![endif]-->
<!--[if IE 9 ]>    <html class="ltr fr no-js ie ie9 lte9" xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr" dir="ltr"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="ltr fr no-js" xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr" dir="ltr"> <!--<![endif]-->
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type='text/javascript'>/*<![CDATA[*/
var url_menu_rubrique="../spip.php?action=menu_rubriques\x26date=1608317543";
(function(H){H.className=H.className.replace(/\bno-js\b/,'js')})(document.documentElement);
 
function test_accepte_ajax(){jQuery.ajax({"url":"https://site.fr/ecrire/?exec=test_ajax\x26js=1"});}
var ajax_image_searching = '<img src="../prive/themes/spip/images/searching.gif" alt="" />';
var stat = 1;
var confirm_changer_statut = 'Attention, vous avez demandÃ© Ã  changer le statut de cet Ã©lÃ©ment. Souhaitez-vous continuerÂ ?';
var error_on_ajaxform='Oups. Une erreur inattendue a empÃªchÃ© de soumettre le formulaire. Vous pouvez essayer Ã  nouveau.';
/*]]>*/</script>
<meta name="viewport" content="width=device-width" />
<link rel="stylesheet" type="text/css" href="https://site.fr/prive/themes/spip/reset.css?1601368394" id="csspriveereset" />
<script type="text/javascript">/* <![CDATA[ */
var box_settings = {tt_img:true,sel_g:"#portfolios a[type^='image/']",sel_c:".mediabox, .iconifier a[href$=jpg],.iconifier a[href$=png],.iconifier a[href$=gif]",trans:"elastic",speed:"200",ssSpeed:"3000",maxW:"90%",maxH:"95%",minW:"600px",minH:"300px",opa:"0.9",str_ssStart:"Diaporama",str_ssStop:"ArrÃªter",str_cur:"{current}/{total}",str_prev:"PrÃ©cÃ©dent",str_next:"Suivant",str_close:"Fermer",splash_url:""};
var box_settings_splash_width = "600px";
var box_settings_splash_height = "90%";
var box_settings_iframe = true;
/* ]]> */</script>
<link rel='stylesheet' type='text/css' media='all' href='../plugins-dist/jquery_ui/css/ui/jquery-ui.css' />
<link rel="stylesheet" href="../plugins-dist/mediabox/prive/colorbox/white-shadow/colorbox.css" type="text/css" media="all" /><link rel='stylesheet' type='text/css' media='all' href='../plugins-dist/porte_plume/css/barre_outils_prive.css?1601368400' />
<link rel='stylesheet' type='text/css' media='all' href='../plugins-dist/porte_plume/css/barre_outils.css?1601368400' />
<link rel='stylesheet' type='text/css' media='all' href='../local/cache-css/cssdyn-css_barre_outils_icones_css-40826303.css?1586262067' />
<link rel="stylesheet" type="text/css" href="https://site.fr/prive/themes/spip/style_prive_defaut.css?1601368394" id="csspriveedef" />
<link rel="stylesheet" type="text/css" href="https://site.fr/prive/spip_admin.css?1601368394"/>
<link rel="stylesheet" type="text/css" href="../spip.php?page=style_prive.css&amp;v=22653&amp;p=16ec&amp;themes=spip&amp;ltr=left&amp;md5b=1f823657ba8e12a3b3388af550475f47&amp;couleur_claire=C5E41C&amp;couleur_foncee=9DBA00" />
```

**Comment by kay0u** [comment]
Bonjour,

Puis-je avoir les logs de la page avec la console développeur?

On dirait qu'il manque de bouts :confused:

**Comment by majoux** [comment]
Pas grand chose dans la console de l'outil de développement de firefox :
`Content Security Policy: Ce site (https://site) possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.`

Et dans la console du navigateur : 
`[Exception... "Favicon at "https://site/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 227"  data: no]`

**Comment by kay0u** [comment]
Pas grand chose en effet.

Y-a-t-il des logs nginx ou php7.2-fpm qui pourrait nous aider?

**Comment by kay0u** [comment]
Pouvez vous essayer de changer de navigateur et/ou désactiver adblocker si vous en avez un?

**Comment by majoux** [comment]
Voici le log nginx error : (j'ai essayé d'anonymiser)
`2021/01/13 14:04:02 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:02 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:02 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:02 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:03 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:03 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:03 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:03 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:17 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:18 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?page=login&url=.%2F"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:23 [error] 3282#3282: *29900 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 192.168.1.86, server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/"
2021/01/13 14:04:26 [error] 3282#3282: *29949 open() "/var/www/spip/ynh_portal.js" failed (2: No such file or directory), client: [IPV6], server: site.fr, request: "GET /ynh_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?article312"
2021/01/13 14:04:26 [error] 3282#3282: *29949 open() "/var/www/spip/ynh_overlay.css" failed (2: No such file or directory), client: [IPV6], server: site.fr, request: "GET /ynh_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?article312"
2021/01/13 14:04:26 [error] 3282#3282: *29949 open() "/var/www/spip/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: [IPV6], server: site.fr, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?article312"
2021/01/13 14:04:26 [error] 3282#3282: *29949 open() "/var/www/spip/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: [IPV6], server: site.fr, request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "site.fr", referrer: "https://site.fr/spip.php?article312"
2021/01/13 14:04:29 [error] 3282#3282: *29900 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/spip/ecrire/inc/filtres_images_lib_mini.php:453
Stack trace:
#0 /var/www/spip/plugins-dist/filtres_images/filtres/images_transforme.php(389): _imagecreatefrompng('../prive/images...')
#1 /var/www/spip/ecrire/inc/filtres.php(457): image_recadre('../prive/images...', '32', '32', 'center')
#2 /var/www/spip/ecrire/inc/filtres.php(266): image_filtrer(Array)
#3 /var/www/spip/tmp/cache/skel/html_dad475ceba8bd3cce1e09dd9831b8c50.php(38): filtrer('image_recadre', '<img src='../pr...', '32', '32', 'center')
#4 /var/www/spip/ecrire/public/parametrer.php(128): html_dad475ceba8bd3cce1e09dd9831b8c50(Array, Array)
#5 /var/www/spip/ecrire/public/assembler.php(314): public_parametrer_dist('prive/squelette...', Array, '03a89ab38ef7609...', NULL)
#6 /var/www/spip/ecrire/public/assembler.php(278): public_produire_page_dist('prive/squelette...', Array, 1, '03a89ab38ef7609...', Array, Array, 0, NULL)
#7 /var/www/spip/ecri" while reading response header from upstream, client: 192.168.1.86, server: site.fr, request: "GET /ecrire/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm-spip.sock:", host: "site.fr", referrer: "https://site.fr/"`

**Comment by majoux** [comment]
Le log php7.3-fpm ne donne rien : 
`[12-Jan-2021 21:27:53] NOTICE: Terminating ...
[12-Jan-2021 21:27:53] NOTICE: exiting, bye-bye!
[12-Jan-2021 21:28:11] NOTICE: fpm is running, pid 2605
[12-Jan-2021 21:28:11] NOTICE: ready to handle connections
[12-Jan-2021 21:28:11] NOTICE: systemd monitor interval set to 10000ms
[12-Jan-2021 21:39:06] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful

[12-Jan-2021 22:46:13] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful

[12-Jan-2021 22:46:25] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful

[12-Jan-2021 22:48:23] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful

[12-Jan-2021 22:50:16] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful

[13-Jan-2021 07:20:46] NOTICE: configuration file /etc/php/7.3/fpm/php-fpm.conf test is successful`

**Comment by majoux** [comment]
J'ai essayé avec le navigateur epiphany (sur lequel je n'ai pas de bloqueur ni de plugin) avant de créer l'issue.
Firefox sans extensions donne le même résultat.
Sur téléphone pareil (avec fenec) : page blanche !

**Comment by kay0u** [comment]
> FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefrompng()

Pouvez vous installer le paquet php7.2-gd:

```
sudo apt install php7.2-gd
```

**Comment by majoux** [comment]
Problem solved !
Merci beaucoup !
C'est bizarre car j'avais déjà le paquet php7.3-gd installé...

**Comment by kay0u** [comment]
Oui mais spip fonctionne avec php7.2 et non php7.3

Super je vais corriger ça dans le paquet! Merci beaucoup pour le retour et désolé pour le dérangement
