### ISSUE TITLE
impossible to reinstall spip

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/spip_ynh#20]
After upgrading from 3.2.7 to 3.2.8 I had a blank private interface.
I made a mistake (I don't know well enough yunohost), by removing config/connect.php as I use to on my different spip installations. 
I tryed to remove the spip installation but I can't install it back again
https://paste.yunohost.org/raw/bapigisosu

**Comment by tutle** [comment]
solved in the last yunohost update
But unable to reinstall the database

**Comment by Aeris1One** [comment]
What error when trying to update the database ? Are you trying using internal Spip database restorer or PHPMyAdmin ?

**Comment by tutle** [comment]
I can't use the internal spip database restorer because some table (the 
most important) are empty when I do internal spip backup. I only have a 
valid spip.sql (working in wampserver)
I tried different thing trough phpmyadmin : empty, rename, import (also 
by excluding authors and meta...) but each time I can't use private 
space in spip any more (no private access problem sql) and the only way 
to recover is to uninstall, reinstall spip (totally new and blank)

Le 12/01/2021 à 20:01, Aeris One a écrit :

**Comment by tutle** [comment]
Until updating 3.2.7 to 3.2.8 all was working fine. my site crashed 
after updating...

Le 12/01/2021 à 20:01, Aeris One a écrit :

**Comment by kay0u** [comment]
Hi,

I don't understand why you are talking about spip.sql since spip in YunoHost uses mysql :confused:

**Comment by tutle** [comment]
When I make export from phpmyadmin , I have a sql file
I have a copy of the working spip db but impossible to copy data in the new db
After upgrading to 3.2.8, my site didn't work anymore (public message "site not configured" and in private /ecrire space "problem sql") so I renamed connect.php as I use to repair my sites from 12 years (but outside yunohost) when upgrading bugs
From now, I have a new blank spip install with no data except the folders IMG, plugins, squelette.
Maybe a solution trough connect.php and users privileges but password encryption are differents
I tried a restore of spip but have an error message.

**Comment by kay0u** [comment]
Are you trying to migrate from your spip website to a spip managed by YunoHost?

May I have the log of the restore?

**Comment by kay0u** [comment]
If it was working before the upgrade, you should have a backup of the app in the YunoHost admin panel with the name `    /home/yunohost.backup/archives/spip-pre-upgrade1.tar` (or 2). You can remove your app, and restore it with this backup

**Comment by tutle** [comment]
My site was working fine on yunohost before upgrading to 3.2.8
There is no pre spip upgrade backup.
Also there was an update of yunohost 4.1.4.4 to make installation of spip possible again.
There is no simple solution to have spip working again with my data ?

**Comment by tutle** [comment]
I'm very disapointed, first time in 12 years my site is out of order from 5 days now and I need it in that time of course...

**Comment by kay0u** [comment]
I feel very sorry for you :confused: 

Can you give me the result of
`sudo yunohost backup list | grep spip`

**Comment by tutle** [comment]
- spip-pre-upgrade2 

after a thousand experiments... restore, copy, exports, from 3 days...
I have the good database (in 3.2.7) ready to use on phpmyadmin but HOW to use it ?

**Comment by kay0u** [comment]
Can you come to the channel support: https://yunohost.org/#/help
It will be easier to help you :-)

**Comment by kay0u** [comment]
It was a mistake on my side, installing `php7.2-gd` was the solution
