### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by kay0u** [YunoHost-Apps/spip_ynh#22]
During the upgrade of spip we remove the file `config/connect.php` and recreate it by going to the web page `/ecrire`

It has been working since a while... except for one person who contacted me for support. Indeed there was no more `config/connect.php` file but we couldn't access the web page `/ecrire`. We have instead of the configuration page the message:

>  Attention : un problème technique (serveur SQL) empêche l’accès à cette partie du site. Merci de votre compréhension. 

Ping @brunob Do you have any idea why?

cc @tutle

**Comment by brunob** [comment]
On cause fr ou en ? ^^

It sounds like an opcache bug, try to hit /ecrire/?exec=install directly instead, it should fix the bug.

**Comment by kay0u** [comment]
> On cause fr ou en ? ^^

L'un ou l'autre, je m'en fiche, si on trouve une solution, en anglais elle sera accessible au plus grand nombre.

> It sounds like an opcache bug, try to hit /ecrire/?exec=install directly instead, it should fix the bug.

I tried, but it didn't work either. Maybe if we restart php fpm

@tutle If you want to debug your issue, move the config/connect.php, and try to restart the php7.2-fpm service:
```
sudo systemctl restart php7.2-fpm
```
Then try to hit you.domain.tld/spip/ecrire
