### ISSUE TITLE
Perte d'indexation

### ISSUE THREAD

**Issue by majoux** [YunoHost-Apps/spip_ynh#28]
Il y a moins d'un mois, les statistiques du site dont je m'occupe se sont effondrées : plus aucun lien ne provient de google. Il semble que ce soit suite à une mise à jour de spip.
En cherchant, je n'arrive pas à accéder au fichier robots.txt d'où la perte d'indexation ?
Que puis-je vérifier ?

Spip Version 3.2.9~ynh2

**Comment by chankalan** [comment]
Il faudrait déjà vérifier que dans le dossier squelettes-dist il y a bien robots.txt.html et sitemap.xml.html, et j'imagine que les statistiques sont bel et bien toujours activées... par précaution :o)

**Comment by majoux** [comment]
Ils existent, les statistiques sont activées et enregistrent quelques visiteurs par jour mais qui ne viennent pas de google.
La page : https://site.com/spip.php?page=robots.txt donne un contenu correct mais la page https://site.com/robots.txt affiche la page d'accueil.
Ce ne serait pas un fichier de conf nginx qui a changé ?

**Comment by majoux** [comment]
Dans le fichier /etc/nginx/conf.d/site.com/spip.conf on trouve ceci :

```
location / {
...
        if (!-e $request_filename)
        {
                rewrite ^/([^/]*)/robots\.txt$    /spip.php?page=robots.txt    last;
                rewrite ^/([^/]*)/sitemap\.xml$   /spip.php?page=sitemap.xml   last;
                rewrite ^(.+)$ /index.php?q=$1 last;
        }
```

Je ne m'y connais pas assez pour savoir s'il y a une erreur. Mais ce que je comprends, c'est qu'à priori la page https://site.com/robots.txt doit renvoyer sur https://site.com/spip.php?page=robots.txt et ce n'est pas ce qui se passe. Quelqu'un aurait une idée ?

**Comment by majoux** [comment]
De même : https://site.com/spip.php?page=favicon.ico fonctionne sans soucis alors que https://site.com/favicon.ico renvoie une erreur 404
La ligne correspondante dans le fichier de conf ne fait pas son job :
`rewrite ^/([^/]*)/favicon\.ico$   /spip.php?page=favicon.ico   last;`

**Comment by kay0u** [comment]
It should be fix now
