### ISSUE TITLE
Miniature picture size

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/spip_ynh#37]
Hello, since upgraded to spip 4 I don't have any more reduced miniatures pictures on public space, only in private space
Any idea where it can come from ?

I could choose before between doc or emb to decide the size...

**Comment by tutle** [comment]
super merci. ça refonctionne sauf pour les vidéos et les diaporamas <articlexxx|cycle>.
et j'ai depuis peu ce message d'erreur
`<html><body>

Aucun squelette modeles/application n’est disponible... | plugins/auto/historique_spip32_documents/v1.0.6/modeles/emb.html | / | 2
-- | -- | -- | --

</body>
</html>`

**Comment by tutle** [comment]
Bonjour, j'ai un souci avec ce plugin, qui ne veut pas afficher les fichiers vidéos..
![erreur spip](https://user-images.githubusercontent.com/23037149/145684256-70c51c9f-fcbf-44ac-a1ea-27f9c310c6b5.jpg)
.

**Comment by chankalan** [comment]
Bonjour,
il serait préférable de remonter les problèmes sur la page du plugin, il y aurait plus de monde pour répondre : https://git.spip.net/spip-contrib-extensions/historique_spip32_documents/issues

**Comment by tutle** [comment]
C'est ce que je comptais faire mais impossible de me connecter sur  https://git.spip.net

**Comment by chankalan** [comment]
Il est possible de créer un ticket sans pour autant être enregistré...

**Comment by tutle** [comment]
Négatif, pas possible visiblement.

**Comment by chankalan** [comment]
En effet, je ne pensais pas... alors est-ce que tu peux demander la création de compte git sur un liste SPIP, ou alors juste faire part du problème du mettant le nom du plugin dans le titre ?
https://discuter.spip.net/

**Comment by rodinux** [comment]
closed as it is a issue from specific plugin not related to yunohost
