### ISSUE TITLE
Any update to spip 4.3.4 planified ?

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/spip_ynh#75]
Hello, I'm using spip for 3 website since 2009 and have a recent problem on one of these.
All 3 are on 4.2.6~ynh2, latest spip release installable on yunohost 11.3.0.2 (current spip should be 4.3.4) and have pretty similar configuration
On one, when I try to connect, I just have this answer and no acces to private section.
```
Vous êtes enregistré... par ici...
Si votre navigateur n’est pas redirigé, cliquez ici pour continuer.
```
How can I solve this issue ? 
Also a trouble with escal plugin no more multi column presentation
Sincerely
Yvan

**Comment by tutle** [comment]
I solved by restore an old backup, but it should be fine to update spip release to 4.3.3
https://discuter.spip.net/t/probleme-de-cookie-spip/154601/3

**Comment by rodinux** [comment]
Upgrade to 4.3.5 now available.
